### ISSUE TITLE
Failed loading /home/zaman/Documents/ZendStudio/plugins/com.zend.php.executables.linux_7.1.3.201703171134/resources/ext/./ext/ZendDebugger.so:  /home/zaman/Documents/ZendStudio/plugins/com.zend.php.executables.linux_7.1.3.201703171134/resources/ext/./ext/ZendDebugger.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zamansandhu** [zendframework/tutorials#89] opened 2017-11-28 07:45 UTC
have issue with this error

**Comment by froschdesign** [comment] 2017-11-28 15:09
Duplicate of zendframework/zendframework/issues/7776

**Closed as completed by froschdesign** 2017-11-28 15:09 UTC
Labels: invalid
